### ISSUE TITLE
Question regarding other models (apart from sciner/scire-scibert)

### ISSUE THREAD

**Issue by Clemens123** [thunlp/PL-Marker#14]
Hi, I'm relatively new to the topic of relation extraction (RE) and I have a few questions you might be able to help with:

- As far as I understand it, each RE-model is a classifier trained specifically on the labels from the dataset; That is, if I need other relation-types, do I need to retrain the whole network? Or is it possible to only retrain the head of the network?
- Are the RE-models using the previously determined named entities with or without label? Could you use the output of an ACE-NER model as input for a SCI-RE model?

I hope you have the time to answer these questions, if not, I would also appreciate a link to a paper/website explaining these issues. Thanks for your work!

**Comment by YeDeming** [comment]
Hi,
I. I haven't done any experiments about switching relation-types. You can search for papers about transfer learning and continuous learning.
2. Since the ACE-NER type contains `['FAC', 'WEA', 'LOC', 'VEH', 'GPE', 'ORG', 'PER']` and the SCI-NER type contains `['Method', 'OtherScientificTerm', 'Task', 'Generic', 'Material', 'Metric']`. The NER model for ACE cannot be used for SCI. For example, the ACE-NER model regards the Method entity as no type.  Specially, the CoNLL03-NER type contains `[MISC]`, which means other-type entities. Hence, the CoNLL03-NER may contains more possible entities.

**Comment by Clemens123** [comment]
Thank you very much for the answers, you helped me very much :)
