### ISSUE TITLE
Issues regarding trained model inference

### ISSUE THREAD

**Issue by P0L3** [thunlp/PL-Marker#53]
No "bash run_train_re.sh" in the repository and no available checkpoints. More detailed tutorial on model inference should be given.

**Comment by YeDeming** [comment]
bash: https://github.com/thunlp/PL-Marker/blob/master/scripts/run_train_re.sh


### Trained Models
We release our trained NER models and RE models on ACE05 and SciERC datasets on [Google Drive](https://drive.google.com/drive/folders/1k_Nt_DeKRKIRd2sM766j538b1JhYm4-H?usp=sharing)/[Tsinghua Cloud](https://cloud.tsinghua.edu.cn/d/5e4a117bc0e5407b9cee/). And we release our trained models on flat NER datasets on  [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/d/5e4a117bc0e5407b9cee/).

*Note*: the performance of the models might be slightly different from the reported numbers in the paper, since we reported the average numbers based on multiple runs.
