### ISSUE TITLE
CoNLL03 data issues

### ISSUE THREAD

**Issue by Dimiftb** [thunlp/PL-Marker#6]
Hi there, 

I'm having issues with trying to replicate the results on conll2003 dataset. I have downloaded the data from the official repo and placed it under `conll03`, so it looks like this: 

![image](https://user-images.githubusercontent.com/26279721/145025915-652084ee-0a8b-4cd4-8a51-b0d10c32e0a4.png)

However, when running I'm getting the following error: 

![image](https://user-images.githubusercontent.com/26279721/145026220-bb0acfa8-8a4e-437b-bd8b-0f4c7d6a4dc7.png)

Additionally, I tried obtaining the dataset from here: https://github.com/davidsbatista/NER-datasets/tree/master/CONLL2003 and renaming the files according to what your model expects, however I'm getting the same error. 
Could you please provide a link for the specific dataset you've used or instructions on how to go about solving this? Thank you.

**Comment by YeDeming** [comment]
You can find it in https://drive.google.com/drive/folders/1ZxytgzPLTA7ge9sX-JgIoIZj7kUCdh9h?usp=sharing

**Comment by Dimiftb** [comment]
Thank you for your swift reply. 

I downloaded the dataset you provided, however I'm getting the same error as before ie. `ValueError: num_samples should be a positive integer value, but got num_samples=0`

**Comment by YeDeming** [comment]
It seems that the code fail to read the file.

The normal script likes:
`
12/07/2021 20:56:01 - INFO - __main__ -    entity_id = 10014
12/07/2021 20:56:01 - INFO - __main__ -    mask_id = 50264
pad: 50261 50262
219554it [00:00, 1164998.07it/s]
160it [00:01, 92.22it/s]
`
rather than 
`
0it
0it
`
The code works in my computer. It  read the input file in
https://github.com/thunlp/PL-Marker/blob/caf67d8542aa14be57a6b6c0201367ec0f6c1aef/run_ner.py#L127-L129

**Comment by Dimiftb** [comment]
Thank you for pointing me to the specific part of the code that opens the file. I managed to find what the issue was. I was downloading the data files the wrong way. Thanks for your help, closing this now.
